# Generated by Django 3.1 on 2022-07-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_image', '0002_auto_20220729_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='cat',
        ),
    ]
