# Generated by Django 3.1 on 2022-07-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_image', '0003_remove_galleryimage_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='is_icon',
        ),
        migrations.AddField(
            model_name='imageitem',
            name='is_icon',
            field=models.BooleanField(default=False),
        ),
    ]
