# Generated by Django 3.1 on 2022-07-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('product', '0002_auto_20220729_1654'),
        ('product_category', '0002_auto_20220729_1654'),
        ('gallery_image', '0005_auto_20220729_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_item', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_item', to='product_category.productcategory'),
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_item', to='product.defineproduct'),
        ),
    ]
