version: "3"

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    container_name: teamShop_postgres
    restart: always

  django:

    build: .
    entrypoint: /django.sh
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8282:8282
    volumes:
      - django_volume:/team_shop
    container_name: teamShop_api
    restart: always

  nginx:
    # after the service is up run /nginx_ssl.sh inside the container
    depends_on:
      - django
    build: nginx
    volumes:
      - django_volume:/team_shop
      - nginx_log_volume:/var/log/nginx
      - nginx_conf_volume:/etc/nginx/conf.d/

    ports:
      - 80:80
      - 443:443
    container_name: teamShop_nginx
    restart: always


volumes:

  postgres_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/team_shop/volumes'

  django_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/team_shop/volumes'

  nginx_log_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/team_shop/volumes'

  nginx_conf_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/root/team_shop/volumes'

