version: "3"

services:
  dev-db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dev_database:/var/lib/postgresql/data/
    ports:
      - 5434:5432


volumes:
  dev_database:

