# Generated by Django 3.1 on 2022-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220729_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='defineproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
