# Generated by Django 3.1 on 2022-07-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220729_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
