# Generated by Django 3.1 on 2022-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220730_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defineproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
