# Generated by Django 3.1 on 2022-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
