# Generated by Django 3.1 on 2022-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220730_1004'),
        ('product_tag', '0002_producttag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='product',
            field=models.ManyToManyField(related_name='tag', to='product.DefineProduct'),
        ),
    ]
